# Semantic Example Configuration
tables:
  papers:
    source: "work/papers.csv"
    column_config:
      - COLUMN,pid,0,uint64
      - COLUMN,title,1,string
      - COLUMN,abstract,2,string
      - PROJECTION,ATitle,0,1,1:1
      - PROJECTION,AAbs,0,2,1:1
      - PROJECTION,BTitle,0,1,1:1
      - PROJECTION,BAbs,0,2,1:1
      - PROJECTION,CTitle,0,1,1:1
      - PROJECTION,CAbs,0,2,1:1
  paper_edges:
    source: "work/paper_edges.csv"
    column_config:
      - COLUMN,src,0,uint64
      - COLUMN,dst,1,uint64
      - PROJECTION,AB,0,1,m:n
      - PROJECTION,BC,0,1,m:n
      - PROJECTION,R,0,1,m:n
